### PR TITLE
Fetch readable web content on demand

### PR DESCRIPTION
**Pull request by cscarney**
Integrate the readability code from @plata's [merge request on Alligator](https://invent.kde.org/plasma-mobile/alligator/-/merge_requests/32).  Depends on the [qreadable](https://github.com/cscarney/qreadable) binary being installed, which was created specifically for this purpose.

### CODE REVIEW

**Comment by plata** [comment]
- Why is Flatpak an issue? It should be possible to include readability-cli in the Flatpak.
- Android: that's true. It could be implemented as a Qt Android Service but if Android is not the main target system, I would just live with the limitation.
- Licensing: Why should this be a problem? You do not include it in your application. Calling an external application should be perfectly fine.

**Comment by cscarney** [comment]
Readability-cli pulls in nodejs and a bunch of other node packages that would also have to be bundled.  That's a lot of bloat for one feature.  I might end up having to do that anyway, but I'm first going to see if I can get readability working with QJSEngine.

I'm not worried about android feature parity right now.  I'll probably just exclude this feature from the android build.

I'm worried about licensing issues with *your* code.  KDE's GPL template is slightly more restrictive than the 3-or-later that I'm using.

**Comment by plata** [comment]
I see. If QJSEngine works, I'm definitely interested in the implementation.

To be honest, I didn't even think about the licensing of my code. From what I'm concerned anybody can use it as they like. I just copy+pasted the license header of the other files in Alligator... Also, I'm not too sure if that could be claimed at all because the code is rather trivial.

**Comment by plata** [comment]
Looking good!

One thing maybe worth thinking about: When should the full content be loaded? When updating the feed or only when viewing the article?<br>
When viewing the article has the advantage that only relevant data is loaded. When updating the feed allows for reading feeds offline and may be a smoother user experience with slow Internet connection (because you don't have to wait for the feed to be loaded). The feed readers which I've used so far would load when updating the feed.

Some other remarks:
- Do you want to use qreadable as library in this PR or only later?
- The readabilitycli wrapper should be renamed for qreadable.
- `Context::supportsReadability()` should not know about the executable name (qreadable).

**Comment by cscarney** [comment]
• For now, I'm going to stick with a separate process.  qreadable is a brand new project and I don't want qreadable bugs taking down the main application process.

• I don't particularly like the idea of requesting every article at update time.  It makes for very slow updates and can trigger CAPTCHAs on the server side, particularly when loading a large feed for the first time.

I intend to add some form of pre-fetching in the future, but probably something more like "load the next few articles while you read" rather than "fetch every article at update time".

• And yes, there are several code quality issues to resolve before merging

**Pull request merged**
